apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: "front-service"
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  type: NodePort
  selector:
    app: "front-selector"
